AllCops:
  Include:
    - '**/Gemfile'
    - lib/**/*
    - spec/**/*
    - usblamp.gemspec
  Exclude:
    - files/**/*
    - templates/**/*
MethodLength:
  Exclude:
    - lib/**/*
ClassLength:
  Exclude:
    - lib/**/*
ParameterLists:
  Exclude:
    - lib/**/*
Metrics/CyclomaticComplexity:
  Exclude:
    - lib/**/*
Metrics/PerceivedComplexity:
  Exclude:
    - lib/**/*
Metrics/AbcSize:
  Exclude:
    - lib/**/*
